package boxmgr

import (
	"bytes"
	"context"
	"crypto/rand"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"
	"time"

	"easy_proxies/internal/config"
	"easy_proxies/internal/storage"
)

var errScriptSourcesUnavailable = errors.New("脚本源管理未启用（请启用数据库存储）")

// ListScriptSources returns all configured script sources.
func (m *Manager) ListScriptSources(ctx context.Context) ([]storage.ScriptSource, error) {
	if ctx != nil {
		if err := ctx.Err(); err != nil {
			return nil, err
		}
	}
	if m.store == nil {
		return nil, errScriptSourcesUnavailable
	}
	return m.store.LoadScriptSources(ctx)
}

// CreateScriptSource creates a new script source and persists it.
func (m *Manager) CreateScriptSource(ctx context.Context, src storage.ScriptSource) (storage.ScriptSource, error) {
	if ctx != nil {
		if err := ctx.Err(); err != nil {
			return storage.ScriptSource{}, err
		}
	}
	if m.store == nil {
		return storage.ScriptSource{}, errScriptSourcesUnavailable
	}

	normalized, err := normalizeScriptSourceInput(src)
	if err != nil {
		return storage.ScriptSource{}, err
	}
	normalized.ID = newRandomHexID(16)
	normalized.CreatedAt = time.Now()
	normalized.UpdatedAt = normalized.CreatedAt

	sources, err := m.store.LoadScriptSources(ctx)
	if err != nil {
		return storage.ScriptSource{}, fmt.Errorf("load script sources: %w", err)
	}
	if hasScriptSourceNameConflict(sources, normalized.ID, normalized.Name) {
		return storage.ScriptSource{}, errors.New("脚本源名称已存在")
	}
	sources = append(sources, normalized)
	if err := m.store.SaveScriptSources(ctx, sources); err != nil {
		return storage.ScriptSource{}, fmt.Errorf("save script sources: %w", err)
	}
	return normalized, nil
}

// UpdateScriptSource updates an existing script source by id and persists it.
func (m *Manager) UpdateScriptSource(ctx context.Context, id string, src storage.ScriptSource) (storage.ScriptSource, error) {
	if ctx != nil {
		if err := ctx.Err(); err != nil {
			return storage.ScriptSource{}, err
		}
	}
	if m.store == nil {
		return storage.ScriptSource{}, errScriptSourcesUnavailable
	}

	id = strings.TrimSpace(id)
	if id == "" {
		return storage.ScriptSource{}, errors.New("脚本源 ID 不能为空")
	}

	normalized, err := normalizeScriptSourceInput(src)
	if err != nil {
		return storage.ScriptSource{}, err
	}

	sources, err := m.store.LoadScriptSources(ctx)
	if err != nil {
		return storage.ScriptSource{}, fmt.Errorf("load script sources: %w", err)
	}

	idx := -1
	for i := range sources {
		if sources[i].ID == id {
			idx = i
			break
		}
	}
	if idx < 0 {
		return storage.ScriptSource{}, errors.New("脚本源不存在")
	}
	if hasScriptSourceNameConflict(sources, id, normalized.Name) {
		return storage.ScriptSource{}, errors.New("脚本源名称已存在")
	}

	prev := sources[idx]
	normalized.ID = prev.ID
	normalized.CreatedAt = prev.CreatedAt
	normalized.UpdatedAt = time.Now()
	sources[idx] = normalized

	if err := m.store.SaveScriptSources(ctx, sources); err != nil {
		return storage.ScriptSource{}, fmt.Errorf("save script sources: %w", err)
	}
	return normalized, nil
}

// DeleteScriptSource deletes a script source by id. It also prunes nodes that were generated by it.
func (m *Manager) DeleteScriptSource(ctx context.Context, id string) error {
	if ctx != nil {
		if err := ctx.Err(); err != nil {
			return err
		}
	}
	if m.store == nil {
		return errScriptSourcesUnavailable
	}

	id = strings.TrimSpace(id)
	if id == "" {
		return errors.New("脚本源 ID 不能为空")
	}

	sources, err := m.store.LoadScriptSources(ctx)
	if err != nil {
		return fmt.Errorf("load script sources: %w", err)
	}

	idx := -1
	for i := range sources {
		if sources[i].ID == id {
			idx = i
			break
		}
	}
	if idx < 0 {
		return errors.New("脚本源不存在")
	}

	sources = append(sources[:idx], sources[idx+1:]...)
	if err := m.store.SaveScriptSources(ctx, sources); err != nil {
		return fmt.Errorf("save script sources: %w", err)
	}

	// Best-effort prune generated nodes from config.
	m.mu.Lock()
	defer m.mu.Unlock()
	if m.cfg == nil {
		return nil
	}
	backup := cloneNodes(m.cfg.Nodes)
	filtered := make([]config.NodeConfig, 0, len(m.cfg.Nodes))
	for _, node := range m.cfg.Nodes {
		if node.Source == config.NodeSourceScript && strings.TrimSpace(node.SourceRef) == id {
			continue
		}
		filtered = append(filtered, node)
	}
	m.cfg.Nodes = filtered
	if err := m.persistNodesLocked(ctx); err != nil {
		m.cfg.Nodes = backup
		return fmt.Errorf("save nodes: %w", err)
	}
	return nil
}

// RunScriptSource executes the script source. When apply is true, it swaps nodes from that source and reloads.
func (m *Manager) RunScriptSource(ctx context.Context, id string, apply bool) (storage.ScriptRunResult, error) {
	if ctx != nil {
		if err := ctx.Err(); err != nil {
			return storage.ScriptRunResult{}, err
		}
	}
	if m.store == nil {
		return storage.ScriptRunResult{}, errScriptSourcesUnavailable
	}

	id = strings.TrimSpace(id)
	if id == "" {
		return storage.ScriptRunResult{}, errors.New("脚本源 ID 不能为空")
	}

	// Serialize script execution/apply to avoid concurrent reloads.
	m.scriptMu.Lock()
	defer m.scriptMu.Unlock()

	sources, err := m.store.LoadScriptSources(ctx)
	if err != nil {
		return storage.ScriptRunResult{}, fmt.Errorf("load script sources: %w", err)
	}
	var src *storage.ScriptSource
	for i := range sources {
		if sources[i].ID == id {
			src = &sources[i]
			break
		}
	}
	if src == nil {
		return storage.ScriptRunResult{}, errors.New("脚本源不存在")
	}

	stdout, stdoutTrunc, stderr, stderrTrunc, exitCode, timedOut, durationMs, runErr := runScript(ctx, *src)
	result := storage.ScriptRunResult{
		SourceID:        id,
		ExitCode:        exitCode,
		TimedOut:        timedOut,
		DurationMs:      durationMs,
		Stdout:          stdout,
		StdoutTruncated: stdoutTrunc,
		Stderr:          stderr,
		StderrTruncated: stderrTrunc,
		Applied:         false,
	}
	if runErr != nil {
		result.Error = runErr.Error()
		return result, runErr
	}

	nodes, parseErr := parseScriptNodes(stdout, src.MaxNodes)
	if parseErr != nil {
		result.Error = parseErr.Error()
		return result, parseErr
	}
	result.Nodes = nodes

	if !apply {
		return result, nil
	}

	// Apply: replace nodes from this script source and reload.
	m.mu.RLock()
	cfgCopy := m.copyConfigLocked()
	portMap := m.cfg.BuildPortMap()
	m.mu.RUnlock()
	if cfgCopy == nil {
		applyErr := errors.New("config is not initialized")
		result.Error = applyErr.Error()
		return result, applyErr
	}

	kept := make([]config.NodeConfig, 0, len(cfgCopy.Nodes))
	replaced := 0
	for _, node := range cfgCopy.Nodes {
		if node.Source == config.NodeSourceScript && strings.TrimSpace(node.SourceRef) == id {
			replaced++
			continue
		}
		kept = append(kept, node)
	}
	for i := range nodes {
		n := nodes[i]
		n.Source = config.NodeSourceScript
		n.SourceRef = id
		// Ports/credentials are assigned by NormalizeWithPortMap.
		n.Port = 0
		n.Username = ""
		n.Password = ""
		kept = append(kept, n)
	}
	cfgCopy.Nodes = kept

	if err := m.ReloadWithPortMap(cfgCopy, portMap); err != nil {
		result.Error = err.Error()
		return result, err
	}
	result.Applied = true
	result.ReplacedCount = replaced
	result.ImportedCount = len(nodes)
	return result, nil
}

// TestScript runs an ad-hoc script without persisting or applying any config changes.
// It returns stdout/stderr and the parsed nodes preview.
func (m *Manager) TestScript(ctx context.Context, src storage.ScriptSource) (storage.ScriptRunResult, error) {
	if ctx != nil {
		if err := ctx.Err(); err != nil {
			return storage.ScriptRunResult{}, err
		}
	}

	// Serialize execution to keep resource usage predictable.
	m.scriptMu.Lock()
	defer m.scriptMu.Unlock()

	if strings.TrimSpace(src.ID) == "" {
		src.ID = "test-" + newRandomHexID(8)
	}
	if strings.TrimSpace(src.Name) == "" {
		src.Name = "Test Script"
	}

	normalized, err := normalizeScriptSourceInput(src)
	if err != nil {
		return storage.ScriptRunResult{}, err
	}

	stdout, stdoutTrunc, stderr, stderrTrunc, exitCode, timedOut, durationMs, runErr := runScript(ctx, normalized)
	result := storage.ScriptRunResult{
		SourceID:        normalized.ID,
		ExitCode:        exitCode,
		TimedOut:        timedOut,
		DurationMs:      durationMs,
		Stdout:          stdout,
		StdoutTruncated: stdoutTrunc,
		Stderr:          stderr,
		StderrTruncated: stderrTrunc,
		Applied:         false,
	}
	if runErr != nil {
		result.Error = runErr.Error()
		return result, runErr
	}

	nodes, parseErr := parseScriptNodes(stdout, normalized.MaxNodes)
	if parseErr != nil {
		result.Error = parseErr.Error()
		return result, parseErr
	}
	result.Nodes = nodes
	return result, nil
}

func normalizeScriptSourceInput(src storage.ScriptSource) (storage.ScriptSource, error) {
	src.Name = strings.TrimSpace(src.Name)
	src.Command = strings.TrimSpace(src.Command)
	src.Script = strings.TrimSpace(src.Script)
	if src.Name == "" {
		return storage.ScriptSource{}, errors.New("name 不能为空")
	}
	if src.Command == "" {
		return storage.ScriptSource{}, errors.New("command 不能为空")
	}
	if src.Script == "" {
		return storage.ScriptSource{}, errors.New("script 不能为空")
	}
	if len(src.Script) > 512*1024 {
		return storage.ScriptSource{}, errors.New("script 过大（最大 512KB）")
	}

	// Defaults
	if src.TimeoutMs <= 0 {
		src.TimeoutMs = 15_000
	}
	if src.TimeoutMs > 5*60_000 {
		src.TimeoutMs = 5 * 60_000
	}
	if src.MaxOutputBytes <= 0 {
		src.MaxOutputBytes = 256 * 1024
	}
	if src.MaxOutputBytes > 4*1024*1024 {
		src.MaxOutputBytes = 4 * 1024 * 1024
	}
	if src.MaxNodes <= 0 {
		src.MaxNodes = 2000
	}
	if src.MaxNodes > 20_000 {
		src.MaxNodes = 20_000
	}

	// Normalize args
	if len(src.Args) > 0 {
		args := make([]string, 0, len(src.Args))
		for _, a := range src.Args {
			a = strings.TrimSpace(a)
			if a == "" {
				continue
			}
			args = append(args, a)
		}
		src.Args = args
	}

	// Normalize python requirements
	if len(src.PythonRequirements) > 0 {
		reqs := make([]string, 0, len(src.PythonRequirements))
		seen := make(map[string]struct{})
		for _, r := range src.PythonRequirements {
			r = strings.TrimSpace(r)
			if r == "" {
				continue
			}
			key := strings.ToLower(r)
			if _, ok := seen[key]; ok {
				continue
			}
			seen[key] = struct{}{}
			reqs = append(reqs, r)
		}
		src.PythonRequirements = reqs
	}
	if src.SetupTimeoutMs <= 0 {
		src.SetupTimeoutMs = 60_000
	}
	if src.SetupTimeoutMs > 10*60_000 {
		src.SetupTimeoutMs = 10 * 60_000
	}
	if len(src.PythonRequirements) > 0 {
		// Reasonable upper bound; should fit common use-cases.
		if len(src.PythonRequirements) > 128 {
			return storage.ScriptSource{}, errors.New("python_requirements 太多（最大 128 行）")
		}
		for _, r := range src.PythonRequirements {
			if len(r) > 200 {
				return storage.ScriptSource{}, errors.New("python_requirements 单行过长（最大 200 字符）")
			}
		}
	}

	// Default enabled when omitted (zero value false is meaningful in JSON), keep as provided.
	return src, nil
}

func requirementsNeedPythonSetup(src storage.ScriptSource) bool {
	if len(src.PythonRequirements) == 0 {
		return false
	}
	cmd := strings.ToLower(strings.TrimSpace(src.Command))
	if cmd == "" {
		return false
	}
	base := strings.ToLower(filepath.Base(cmd))
	if strings.HasPrefix(base, "python") {
		return true
	}
	return cmd == "python" || cmd == "python3" || cmd == "py"
}

func scriptCacheDir(sourceID string) string {
	sourceID = strings.TrimSpace(sourceID)
	if sourceID == "" {
		sourceID = "unknown"
	}
	sourceID = strings.Map(func(r rune) rune {
		switch {
		case r >= 'a' && r <= 'z':
			return r
		case r >= 'A' && r <= 'Z':
			return r
		case r >= '0' && r <= '9':
			return r
		case r == '-' || r == '_' || r == '.':
			return r
		default:
			return '_'
		}
	}, sourceID)
	if base := strings.TrimSpace(os.Getenv("EASY_PROXIES_DATA_DIR")); base != "" {
		return filepath.Join(base, "script-sources", sourceID)
	}
	// Prefer XDG cache dir if set.
	if base := strings.TrimSpace(os.Getenv("XDG_CACHE_HOME")); base != "" {
		return filepath.Join(base, "easy-proxies", "script-sources", sourceID)
	}
	// Fallback to user's home.
	if homeDir, err := os.UserHomeDir(); err == nil {
		if strings.TrimSpace(homeDir) != "" {
			return filepath.Join(homeDir, ".cache", "easy-proxies", "script-sources", sourceID)
		}
	}
	// Last resort: temp.
	return filepath.Join(os.TempDir(), "easy-proxies-cache", "script-sources", sourceID)
}

func ensurePythonEnv(ctx context.Context, src storage.ScriptSource) (pythonPath string, err error) {
	resolvedPython, resolveErr := resolvePythonCommand(ctx, src.Command)
	if resolveErr != nil {
		return "", resolveErr
	}
	src.Command = resolvedPython

	cacheDir := scriptCacheDir(src.ID)
	venvDir := filepath.Join(cacheDir, "venv")
	marker := filepath.Join(cacheDir, "requirements.lock")

	pythonInVenv := venvPythonPath(venvDir)

	// Build desired lock text.
	lockText := strings.Join(src.PythonRequirements, "\n") + "\n"
	lockHash := fmt.Sprintf("%x", sha256.Sum256([]byte(lockText)))

	if b, readErr := os.ReadFile(marker); readErr == nil {
		if strings.TrimSpace(string(b)) == lockHash {
			if _, statErr := os.Stat(pythonInVenv); statErr == nil {
				return pythonInVenv, nil
			}
		}
	}

	setupTimeout := time.Duration(src.SetupTimeoutMs) * time.Millisecond
	if setupTimeout <= 0 {
		setupTimeout = 60 * time.Second
	}
	baseCtx := ctx
	if baseCtx == nil {
		baseCtx = context.Background()
	}
	setupCtx, cancel := context.WithTimeout(baseCtx, setupTimeout)
	defer cancel()

	if mkErr := os.MkdirAll(cacheDir, 0o700); mkErr != nil {
		return "", fmt.Errorf("create script cache dir: %w", mkErr)
	}

	// Create venv if missing.
	if _, statErr := os.Stat(pythonInVenv); statErr != nil {
		cmd := exec.CommandContext(setupCtx, src.Command, "-m", "venv", venvDir)
		cmd.Stdout = io.Discard
		stderrCap := &limitedCapture{limit: 64 * 1024}
		cmd.Stderr = stderrCap
		if err := cmd.Run(); err != nil {
			msg := strings.TrimSpace(stderrCap.String())
			if msg != "" {
				return "", fmt.Errorf("create python venv: %w: %s", err, msg)
			}
			return "", fmt.Errorf("create python venv: %w", err)
		}
	}

	// Ensure pip exists (some minimal venv builds may not include it).
	if _, statErr := os.Stat(pythonInVenv); statErr != nil {
		// venv python missing entirely
		return "", errors.New("python venv missing interpreter")
	}
	if _, statErr := os.Stat(venvPipPath(venvDir)); statErr != nil {
		cmd := exec.CommandContext(setupCtx, pythonInVenv, "-m", "ensurepip")
		cmd.Stdout = io.Discard
		cmd.Stderr = io.Discard
		_ = cmd.Run()
	}

	// Install requirements.
	args := []string{"-m", "pip", "install", "--disable-pip-version-check", "--no-input"}
	args = append(args, src.PythonRequirements...)
	cmd := exec.CommandContext(setupCtx, pythonInVenv, args...)
	cmd.Stdout = io.Discard
	stderrCap := &limitedCapture{limit: 64 * 1024}
	cmd.Stderr = stderrCap
	if err := cmd.Run(); err != nil {
		msg := strings.TrimSpace(stderrCap.String())
		if msg != "" {
			return "", fmt.Errorf("pip install failed: %w: %s", err, msg)
		}
		return "", fmt.Errorf("pip install failed: %w", err)
	}

	// Write marker (hash only).
	_ = os.WriteFile(marker, []byte(lockHash+"\n"), 0o600)
	return pythonInVenv, nil
}

func venvPythonPath(venvDir string) string {
	if runtime.GOOS == "windows" {
		return filepath.Join(venvDir, "Scripts", "python.exe")
	}
	return filepath.Join(venvDir, "bin", "python")
}

func venvPipPath(venvDir string) string {
	if runtime.GOOS == "windows" {
		return filepath.Join(venvDir, "Scripts", "pip.exe")
	}
	return filepath.Join(venvDir, "bin", "pip")
}

func hasScriptSourceNameConflict(items []storage.ScriptSource, id, name string) bool {
	nameKey := strings.ToLower(strings.TrimSpace(name))
	if nameKey == "" {
		return false
	}
	for _, item := range items {
		if item.ID == id {
			continue
		}
		if strings.ToLower(strings.TrimSpace(item.Name)) == nameKey {
			return true
		}
	}
	return false
}

func newRandomHexID(nBytes int) string {
	if nBytes <= 0 {
		nBytes = 16
	}
	b := make([]byte, nBytes)
	if _, err := rand.Read(b); err != nil {
		// fallback to time-based value
		return fmt.Sprintf("%d", time.Now().UnixNano())
	}
	return hex.EncodeToString(b)
}

type limitedCapture struct {
	limit     int
	buf       bytes.Buffer
	truncated bool
}

func (w *limitedCapture) Write(p []byte) (int, error) {
	if w == nil {
		return len(p), nil
	}
	if w.limit <= 0 {
		w.truncated = true
		return len(p), nil
	}
	remaining := w.limit - w.buf.Len()
	if remaining <= 0 {
		w.truncated = true
		return len(p), nil
	}
	if len(p) > remaining {
		_, _ = w.buf.Write(p[:remaining])
		w.truncated = true
		return len(p), nil
	}
	_, _ = w.buf.Write(p)
	return len(p), nil
}

func (w *limitedCapture) String() string {
	if w == nil {
		return ""
	}
	return w.buf.String()
}

func runScript(ctx context.Context, src storage.ScriptSource) (stdout string, stdoutTrunc bool, stderr string, stderrTrunc bool, exitCode int, timedOut bool, durationMs int64, err error) {
	if requirementsNeedPythonSetup(src) {
		pythonPath, setupErr := ensurePythonEnv(ctx, src)
		if setupErr != nil {
			return "", false, "", false, -1, false, 0, setupErr
		}
		src.Command = pythonPath
	}

	timeout := time.Duration(src.TimeoutMs) * time.Millisecond
	if timeout <= 0 {
		timeout = 15 * time.Second
	}
	maxOut := src.MaxOutputBytes
	if maxOut <= 0 {
		maxOut = 256 * 1024
	}
	baseCtx := ctx
	if baseCtx == nil {
		baseCtx = context.Background()
	}
	runCtx, cancel := context.WithTimeout(baseCtx, timeout)
	defer cancel()

	tmpDir, tmpErr := os.MkdirTemp("", "easy_proxies-script-")
	if tmpErr != nil {
		return "", false, "", false, -1, false, 0, fmt.Errorf("create temp dir: %w", tmpErr)
	}
	defer os.RemoveAll(tmpDir)

	baseCmd := strings.ToLower(filepath.Base(strings.TrimSpace(src.Command)))
	scriptName := "script"
	if strings.HasPrefix(baseCmd, "python") {
		scriptName = "script.py"
	} else if baseCmd == "py" {
		scriptName = "script.py"
	} else if baseCmd == "pwsh" || strings.Contains(baseCmd, "powershell") {
		scriptName = "script.ps1"
	}
	scriptPath := filepath.Join(tmpDir, scriptName)
	if writeErr := os.WriteFile(scriptPath, []byte(src.Script), 0o600); writeErr != nil {
		return "", false, "", false, -1, false, 0, fmt.Errorf("write script: %w", writeErr)
	}

	argv := make([]string, 0, 1+len(src.Args)+1)
	argv = append(argv, src.Command)
	argv = append(argv, src.Args...)
	if strings.EqualFold(filepath.Base(strings.TrimSpace(src.Command)), "py") {
		// Prefer Python 3 when using Windows py launcher.
		argv = append(argv, "-3")
	}
	argv = append(argv, scriptPath)

	cmd := exec.CommandContext(runCtx, argv[0], argv[1:]...)
	cmd.Dir = tmpDir
	cmd.Env = append(os.Environ(),
		"EP_SOURCE_ID="+strings.TrimSpace(src.ID),
		"EP_SOURCE_NAME="+strings.TrimSpace(src.Name),
	)
	configureScriptProcess(cmd)

	input := map[string]any{
		"source": map[string]any{
			"id":   src.ID,
			"name": src.Name,
		},
		"now": time.Now().UTC().Format(time.RFC3339Nano),
	}
	inputJSON, _ := json.Marshal(input)
	cmd.Stdin = bytes.NewReader(inputJSON)

	stdoutCap := &limitedCapture{limit: maxOut}
	stderrCap := &limitedCapture{limit: maxOut}
	cmd.Stdout = stdoutCap
	cmd.Stderr = stderrCap

	start := time.Now()
	startErr := cmd.Start()
	if startErr != nil {
		return "", false, stderrCap.String(), stderrCap.truncated, -1, false, time.Since(start).Milliseconds(), fmt.Errorf("start script: %w", startErr)
	}

	done := make(chan error, 1)
	go func() {
		done <- cmd.Wait()
	}()

	select {
	case waitErr := <-done:
		duration := time.Since(start)
		exit := 0
		if cmd.ProcessState != nil {
			exit = cmd.ProcessState.ExitCode()
		}
		if waitErr != nil {
			// Keep stdout/stderr for debugging.
			return stdoutCap.String(), stdoutCap.truncated, stderrCap.String(), stderrCap.truncated, exit, false, duration.Milliseconds(), fmt.Errorf("script exit %d: %w", exit, waitErr)
		}
		return stdoutCap.String(), stdoutCap.truncated, stderrCap.String(), stderrCap.truncated, exit, false, duration.Milliseconds(), nil
	case <-runCtx.Done():
		killScriptProcessTree(cmd)
		_ = <-done
		duration := time.Since(start)
		return stdoutCap.String(), stdoutCap.truncated, stderrCap.String(), stderrCap.truncated, -1, true, duration.Milliseconds(), fmt.Errorf("script timeout after %s", timeout)
	}
}

type scriptNodeObject struct {
	Name    string `json:"name"`
	URI     string `json:"uri"`
	URL     string `json:"url"`
	Region  string `json:"region"`
	Country string `json:"country"`
}

func parseScriptNodes(stdout string, maxNodes int) ([]config.NodeConfig, error) {
	text := strings.TrimSpace(stdout)
	if text == "" {
		return nil, errors.New("脚本输出为空（stdout 需要输出 JSON）")
	}

	if maxNodes <= 0 {
		maxNodes = 2000
	}

	var raw any
	dec := json.NewDecoder(strings.NewReader(text))
	dec.UseNumber()
	if err := dec.Decode(&raw); err != nil {
		return nil, fmt.Errorf("解析脚本输出 JSON 失败: %w", err)
	}

	var rawNodes []any
	switch v := raw.(type) {
	case []any:
		rawNodes = v
	case map[string]any:
		if nodesVal, ok := v["nodes"]; ok {
			if arr, ok := nodesVal.([]any); ok {
				rawNodes = arr
			} else {
				return nil, errors.New("脚本输出字段 nodes 必须是数组")
			}
		} else if nodeVal, ok := v["node"]; ok {
			rawNodes = []any{nodeVal}
		} else {
			return nil, errors.New("脚本输出必须包含 nodes 数组")
		}
	default:
		return nil, errors.New("脚本输出 JSON 顶层必须是对象或数组")
	}

	if len(rawNodes) > maxNodes {
		return nil, fmt.Errorf("节点数量过多: %d (max %d)", len(rawNodes), maxNodes)
	}

	out := make([]config.NodeConfig, 0, len(rawNodes))
	seen := make(map[string]struct{}, len(rawNodes))
	for idx, item := range rawNodes {
		if item == nil {
			continue
		}
		switch v := item.(type) {
		case string:
			uri := strings.TrimSpace(v)
			if uri == "" {
				continue
			}
			if _, ok := seen[uri]; ok {
				continue
			}
			seen[uri] = struct{}{}
			out = append(out, config.NodeConfig{URI: uri})
		case map[string]any:
			// Re-marshal to leverage struct tags and keep behavior stable.
			b, _ := json.Marshal(v)
			var obj scriptNodeObject
			if err := json.Unmarshal(b, &obj); err != nil {
				return nil, fmt.Errorf("解析节点对象失败 (index %d): %w", idx, err)
			}
			uri := strings.TrimSpace(obj.URI)
			if uri == "" {
				uri = strings.TrimSpace(obj.URL)
			}
			if uri == "" {
				return nil, fmt.Errorf("节点缺少 uri 字段 (index %d)", idx)
			}
			if _, ok := seen[uri]; ok {
				continue
			}
			seen[uri] = struct{}{}
			out = append(out, config.NodeConfig{
				Name:    strings.TrimSpace(obj.Name),
				URI:     uri,
				Region:  strings.TrimSpace(obj.Region),
				Country: strings.TrimSpace(obj.Country),
			})
		default:
			return nil, fmt.Errorf("不支持的节点类型 (index %d)", idx)
		}
	}

	if len(out) == 0 {
		return nil, errors.New("脚本未返回任何节点")
	}
	return out, nil
}

// Ensure limitedCapture satisfies io.Writer.
var _ io.Writer = (*limitedCapture)(nil)
